# app/tools/city_codes.py

from __future__ import annotations
from typing import Dict, List, Set, Tuple

# --- Minimal but high-signal catalog (expand anytime) -------------------------
# Each entry may be:
#   - a CITY (maps to one or more airports, incl. metro codes),
#   - a METRO code (e.g., LON -> [LHR, LGW, LCY, LTN, STN, SEN]),
#   - or a single AIRPORT code.
#
# IMPORTANT: You can safely extend these dicts without changing any code elsewhere.

CITY_TO_AIRPORTS: Dict[str, List[str]] = {
    # UK / Europe
    "london": ["LON", "LHR", "LGW", "LCY", "LTN", "STN", "SEN"],
    "athens": ["ATH"],
    "rome": ["ROM", "FCO", "CIA"],
    "paris": ["PAR", "CDG", "ORY", "BVA"],
    "milan": ["MIL", "MXP", "LIN", "BGY"],
    "amsterdam": ["AMS"],
    "frankfurt": ["FRA"],
    "munich": ["MUC"],
    "berlin": ["BER", "TXL"],  # BER is the new main airport, TXL was the old one
    "zurich": ["ZRH"],
    "vienna": ["VIE"],
    "barcelona": ["BCN"],
    "madrid": ["MAD"],
    "stockholm": ["STO", "ARN", "BMA"],
    "copenhagen": ["CPH"],
    "oslo": ["OSL"],

    # Middle East
    "dubai": ["DXB", "DWC"],         # DWC sometimes used for LCCs
    "abu dhabi": ["AUH"],
    "doha": ["DOH"],
    "kuwait": ["KWI"],
    "muscat": ["MCT"],
    "bahrain": ["BAH"],
    "jeddah": ["JED"],
    "riyadh": ["RUH"],

    # Türkiye
    "istanbul": ["IST", "SAW"],

    # Pakistan
    "lahore": ["LHE"],
    "karachi": ["KHI"],
    "islamabad": ["ISB"],
    "sialkot": ["SKT"],
    "peshawar": ["PEW"],
    "multan": ["MUX"],
    "quetta": ["UET"],

    # US (common)
    "new york": ["NYC", "JFK", "LGA", "EWR"],
    "chicago": ["CHI", "ORD", "MDW"],
    "los angeles": ["LAX"],
    "san francisco": ["SFO"],
    "miami": ["MIA"],
    "boston": ["BOS"],
    "seattle": ["SEA"],
    "dallas": ["DFW", "DAL"],

    # Asia hubs
    "singapore": ["SIN"],
    "tokyo": ["TYO", "HND", "NRT"],
    "seoul": ["SEL", "ICN", "GMP"],
    "hong kong": ["HKG"],
    "bangkok": ["BKK"],
    "kuala lumpur": ["KUL"],
    "delhi": ["DEL"],
    "mumbai": ["BOM"],

    # Africa (common hubs)
    "nairobi": ["NBO"],
    "johannesburg": ["JNB"],
    "casablanca": ["CMN"],

    # --- UK & Ireland ---
    "manchester": ["MAN"],
    "birmingham": ["BHX"],
    "bristol": ["BRS"],
    "edinburgh": ["EDI"],
    "glasgow": ["GLA"],
    "newcastle": ["NCL"],
    "leeds": ["LBA"],
    "liverpool": ["LPL"],
    "aberdeen": ["ABZ"],
    "inverness": ["INV"],
    "nottingham": ["EMA"],   # East Midlands
    "cardiff": ["CWL"],
    "belfast": ["BFS", "BHD"],
    "isle of man": ["IOM"],
    "jersey": ["JER"],
    "guernsey": ["GCI"],
    "dublin": ["DUB"],
    "cork": ["ORK"],
    "shannon": ["SNN"],

    # --- France ---
    "nice": ["NCE"],
    "marseille": ["MRS"],
    "lyon": ["LYS"],
    "toulouse": ["TLS"],
    "bordeaux": ["BOD"],
    "nantes": ["NTE"],
    "lille": ["LIL"],
    "montpellier": ["MPL"],
    "strasbourg": ["SXB"],
    "rennes": ["RNS"],
    "biarritz": ["BIQ"],
    "bastia": ["BIA"],
    "ajaccio": ["AJA"],

    # --- Spain & Portugal ---
    "valencia": ["VLC"],
    "malaga": ["AGP"],
    "alicante": ["ALC"],
    "seville": ["SVQ"],
    "bilbao": ["BIO"],
    "palma de mallorca": ["PMI"],
    "ibiza": ["IBZ"],
    "tenerife": ["TFS", "TFN"],
    "gran canaria": ["LPA"],
    "lanzarote": ["ACE"],
    "menorca": ["MAH"],
    "santiago de compostela": ["SCQ"],
    "vigo": ["VGO"],
    "oviedo": ["OVD"],
    "zaragoza": ["ZAZ"],
    "lisbon": ["LIS"],
    "porto": ["OPO"],
    "faro": ["FAO"],
    "funchal": ["FNC"],
    "ponta delgada": ["PDL"],
    "terceira": ["TER"],

    # --- Italy ---
    "venice": ["VCE"],
    "verona": ["VRN"],
    "bologna": ["BLQ"],
    "naples": ["NAP"],
    "turin": ["TRN"],
    "florence": ["FLR"],
    "pisa": ["PSA"],
    "bari": ["BRI"],
    "brindisi": ["BDS"],
    "palermo": ["PMO"],
    "catania": ["CTA"],
    "cagliari": ["CAG"],
    "alghero": ["AHO"],
    "trieste": ["TRS"],
    "genoa": ["GOA"],
    "perugia": ["PEG"],

    # --- Germany ---
    "hamburg": ["HAM"],
    "dusseldorf": ["DUS"],
    "cologne": ["CGN"],
    "stuttgart": ["STR"],
    "hannover": ["HAJ"],
    "nuremberg": ["NUE"],
    "leipzig": ["LEJ"],
    "dresden": ["DRS"],
    "bremen": ["BRE"],
    "dortmund": ["DTM"],
    "frankfurt hahn": ["HHN"],

    # --- Switzerland, Austria, Belgium, Netherlands, Nordics, Baltics ---
    "geneva": ["GVA"],
    "basel": ["BSL"],
    "salzburg": ["SZG"],
    "innsbruck": ["INN"],
    "graz": ["GRZ"],
    "linz": ["LNZ"],
    "klagenfurt": ["KLU"],
    "brussels": ["BRU"],
    "charleroi": ["CRL"],
    "antwerp": ["ANR"],
    "ostend": ["OST"],
    "rotterdam": ["RTM"],
    "eindhoven": ["EIN"],
    "maastricht": ["MST"],
    "groningen": ["GRQ"],
    "helsinki": ["HEL"],
    "turku": ["TKU"],
    "tampere": ["TMP"],
    "oulu": ["OUL"],
    "gothenburg": ["GOT"],
    "malmo": ["MMX"],
    "lulea": ["LLA"],
    "umea": ["UME"],
    "billund": ["BLL"],
    "aarhus": ["AAR"],
    "aalborg": ["AAL"],
    "reykjavik": ["KEF", "RKV"],
    "tallinn": ["TLL"],
    "riga": ["RIX"],
    "vilnius": ["VNO"],
    "kaunas": ["KUN"],
    "prague": ["PRG"],
    "brno": ["BRQ"],
    "ostrava": ["OSR"],
    "bratislava": ["BTS"],
    "kosice": ["KSC"],
    "budapest": ["BUD"],
    "debrecen": ["DEB"],

    # --- Balkans & Eastern Europe ---
    "ljubljana": ["LJU"],
    "zagreb": ["ZAG"],
    "split": ["SPU"],
    "dubrovnik": ["DBV"],
    "pula": ["PUY"],
    "zadar": ["ZAD"],
    "rijeka": ["RJK"],
    "sarajevo": ["SJJ"],
    "mostar": ["OMO"],
    "banja luka": ["BNX"],
    "belgrade": ["BEG"],
    "nis": ["INI"],
    "podgorica": ["TGD"],
    "tivat": ["TIV"],
    "skopje": ["SKP"],
    "ohrid": ["OHD"],
    "tirana": ["TIA"],
    "bucharest": ["OTP"],
    "cluj-napoca": ["CLJ"],
    "timisoara": ["TSR"],
    "iasi": ["IAS"],
    "sibiu": ["SBZ"],
    "craiova": ["CRA"],
    "bacau": ["BCM"],
    "sofia": ["SOF"],
    "varna": ["VAR"],
    "burgas": ["BOJ"],
    "chisinau": ["RMO"],

    # --- Türkiye (beyond Istanbul) ---
    "ankara": ["ESB"],
    "izmir": ["ADB"],
    "antalya": ["AYT"],
    "adana": ["ADA"],
    "trabzon": ["TZX"],
    "gaziantep": ["GZT"],
    "kayseri": ["ASR"],
    "bodrum": ["BJV"],
    "dalaman": ["DLM"],
    "konya": ["KYA"],
    "samsun": ["SZF"],
    "erzurum": ["ERZ"],
    "diyarbakir": ["DIY"],
    "van": ["VAN"],
    "mardin": ["MQM"],

    # --- Middle East (expanded) ---
    "sharjah": ["SHJ"],
    "ras al khaimah": ["RKT"],
    "fujairah": ["FJR"],
    "al ain": ["AAN"],
    "dammam": ["DMM"],
    "medina": ["MED"],
    "taif": ["TIF"],
    "abha": ["AHB"],
    "gizan": ["GIZ"],
    "amman": ["AMM", "ADJ"],
    "beirut": ["BEY"],
    "tel aviv": ["TLV"],
    "aqaba": ["AQJ"],
    "salalah": ["SLL"],
    "tehran": ["IKA", "THR"],
    "mashhad": ["MHD"],
    "shiraz": ["SYZ"],
    "tabriz": ["TBZ"],
    "isfahan": ["IFN"],
    "baghdad": ["BGW"],
    "basra": ["BSR"],
    "erbil": ["EBL"],
    "sulaymaniyah": ["ISU"],
    "najaf": ["NJF"],
    "sanaa": ["SAH"],
    "aden": ["ADE"],

    # --- South Asia ---
    "bengaluru": ["BLR"],
    "bangalore": ["BLR"],
    "hyderabad": ["HYD"],
    "chennai": ["MAA"],
    "kolkata": ["CCU"],
    "ahmedabad": ["AMD"],
    "jaipur": ["JAI"],
    "kochi": ["COK"],
    "cochin": ["COK"],
    "trivandrum": ["TRV"],
    "pune": ["PNQ"],
    "goa": ["GOX", "GOI"],
    "lucknow": ["LKO"],
    "amritsar": ["ATQ"],
    "chandigarh": ["IXC"],
    "guwahati": ["GAU"],
    "patna": ["PAT"],
    "varanasi": ["VNS"],
    "coimbatore": ["CJB"],
    "nagpur": ["NAG"],
    "indore": ["IDR"],
    "surat": ["STV"],
    "vadodara": ["BDQ"],
    "bhopal": ["BHO"],
    "srinagar": ["SXR"],
    "leh": ["IXL"],
    "new delhi": ["DEL"],
    "colombo": ["CMB", "RML"],
    "male": ["MLE"],
    "kathmandu": ["KTM"],
    "pokhara": ["PKR"],
    "dhaka": ["DAC"],
    "chittagong": ["CGP"],
    "chattogram": ["CGP"],
    "sylhet": ["ZYL"],
    "paro": ["PBH"],
    "kabul": ["KBL"],
    "herat": ["HEA"],
    "mazar-i-sharif": ["MZR"],
    "kandahar": ["KDH"],

    # --- East Asia ---
    "beijing": ["PEK", "PKX"],
    "shanghai": ["PVG", "SHA"],
    "guangzhou": ["CAN"],
    "shenzhen": ["SZX"],
    "chengdu": ["CTU", "TFU"],
    "chongqing": ["CKG"],
    "xian": ["XIY"],
    "kunming": ["KMG"],
    "hangzhou": ["HGH"],
    "nanjing": ["NKG"],
    "wuhan": ["WUH"],
    "xiamen": ["XMN"],
    "qingdao": ["TAO"],
    "fuzhou": ["FOC"],
    "tianjin": ["TSN"],
    "shenyang": ["SHE"],
    "dalian": ["DLC"],
    "harbin": ["HRB"],
    "sanya": ["SYX"],
    "haikou": ["HAK"],
    "urumqi": ["URC"],
    "guiyang": ["KWE"],
    "zhengzhou": ["CGO"],
    "changsha": ["CSX"],
    "ningbo": ["NGB"],
    "taipei": ["TPE", "TSA"],
    "kaohsiung": ["KHH"],
    "taichung": ["RMQ"],
    "busan": ["PUS"],
    "jeju": ["CJU"],
    "daegu": ["TAE"],
    "gwangju": ["KWJ"],
    "osaka": ["KIX", "ITM"],
    "nagoya": ["NGO"],
    "fukuoka": ["FUK"],
    "sapporo": ["CTS", "OKD"],
    "naha": ["OKA"],
    "hiroshima": ["HIJ"],
    "sendai": ["SDJ"],
    "kagoshima": ["KOJ"],
    "kumamoto": ["KMJ"],
    "niigata": ["KIJ"],

    # --- Southeast Asia ---
    "jakarta": ["CGK", "HLP"],
    "bali": ["DPS"],
    "denpasar": ["DPS"],
    "surabaya": ["SUB"],
    "yogyakarta": ["YIA"],
    "medan": ["KNO"],
    "bandung": ["BDO"],
    "makassar": ["UPG"],
    "balikpapan": ["BPN"],
    "penang": ["PEN"],
    "langkawi": ["LGK"],
    "johor bahru": ["JHB"],
    "kota kinabalu": ["BKI"],
    "kuching": ["KCH"],
    "miri": ["MYY"],
    "manila": ["MNL"],
    "cebu": ["CEB"],
    "clark": ["CRK"],
    "davao": ["DVO"],
    "iloilo": ["ILO"],
    "cagayan de oro": ["CGY"],
    "ho chi minh city": ["SGN"],
    "hanoi": ["HAN"],
    "da nang": ["DAD"],
    "nha trang": ["CXR"],
    "phu quoc": ["PQC"],
    "hue": ["HUI"],
    "phuket": ["HKT"],
    "chiang mai": ["CNX"],
    "krabi": ["KBV"],
    "koh samui": ["USM"],
    "phnom penh": ["PNH"],
    "siem reap": ["REP"],
    "sihanoukville": ["KOS"],
    "vientiane": ["VTE"],
    "luang prabang": ["LPQ"],
    "yangon": ["RGN"],
    "mandalay": ["MDL"],
    "naypyidaw": ["NYT"],
    "bandar seri begawan": ["BWN"],
    "dili": ["DIL"],

    # --- Oceania ---
    "sydney": ["SYD"],
    "melbourne": ["MEL", "AVV"],
    "brisbane": ["BNE"],
    "perth": ["PER"],
    "adelaide": ["ADL"],
    "canberra": ["CBR"],
    "gold coast": ["OOL"],
    "cairns": ["CNS"],
    "hobart": ["HBA"],
    "darwin": ["DRW"],
    "townsville": ["TSV"],
    "newcastle au": ["NTL"],
    "sunshine coast": ["MCY"],
    "auckland": ["AKL"],
    "wellington": ["WLG"],
    "christchurch": ["CHC"],
    "queenstown": ["ZQN"],
    "dunedin": ["DUD"],
    "hamilton nz": ["HLZ"],
    "nadi": ["NAN"],
    "suva": ["SUV"],
    "apia": ["APW"],
    "nuku'alofa": ["TBU"],
    "port vila": ["VLI"],
    "noumea": ["NOU"],
    "papeete": ["PPT"],
    "guam": ["GUM"],
    "saipan": ["SPN"],
    "koror": ["ROR"],
    "majuro": ["MAJ"],
    "pohnpei": ["PNI"],
    "chuuk": ["TKK"],
    "pago pago": ["PPG"],

    # --- North America (USA) ---
    "washington dc": ["IAD", "DCA", "BWI"],
    "houston": ["IAH", "HOU"],
    "phoenix": ["PHX"],
    "philadelphia": ["PHL"],
    "atlanta": ["ATL"],
    "detroit": ["DTW"],
    "minneapolis": ["MSP"],
    "denver": ["DEN"],
    "san diego": ["SAN"],
    "las vegas": ["LAS"],
    "portland": ["PDX"],
    "austin": ["AUS"],
    "san jose": ["SJC"],
    "orlando": ["MCO", "SFB"],
    "tampa": ["TPA"],
    "fort lauderdale": ["FLL"],
    "west palm beach": ["PBI"],
    "charlotte": ["CLT"],
    "raleigh": ["RDU"],
    "nashville": ["BNA"],
    "new orleans": ["MSY"],
    "salt lake city": ["SLC"],
    "baltimore": ["BWI"],
    "cleveland": ["CLE"],
    "cincinnati": ["CVG"],
    "columbus": ["CMH"],
    "pittsburgh": ["PIT"],
    "indianapolis": ["IND"],
    "kansas city": ["MCI"],
    "st louis": ["STL"],
    "sacramento": ["SMF"],
    "oakland": ["OAK"],
    "long beach": ["LGB"],
    "burbank": ["BUR"],
    "orange county": ["SNA"],
    "jacksonville": ["JAX"],
    "san antonio": ["SAT"],
    "el paso": ["ELP"],
    "albuquerque": ["ABQ"],
    "oklahoma city": ["OKC"],
    "tulsa": ["TUL"],
    "memphis": ["MEM"],
    "milwaukee": ["MKE"],
    "hartford": ["BDL"],
    "providence": ["PVD"],
    "buffalo": ["BUF"],
    "rochester ny": ["ROC"],
    "syracuse": ["SYR"],
    "albany": ["ALB"],
    "norfolk": ["ORF"],
    "richmond": ["RIC"],
    "charleston sc": ["CHS"],
    "savannah": ["SAV"],
    "myrtle beach": ["MYR"],
    "charleston wv": ["CRW"],
    "boise": ["BOI"],
    "spokane": ["GEG"],
    "anchorage": ["ANC"],
    "fairbanks": ["FAI"],
    "honolulu": ["HNL"],
    "kahului": ["OGG"],
    "kona": ["KOA"],
    "lihue": ["LIH"],
    "panama city beach": ["ECP"],

    # --- Canada ---
    "toronto": ["YYZ", "YTZ"],
    "montreal": ["YUL", "YHU"],
    "vancouver": ["YVR"],
    "calgary": ["YYC"],
    "edmonton": ["YEG"],
    "ottawa": ["YOW"],
    "winnipeg": ["YWG"],
    "quebec city": ["YQB"],
    "halifax": ["YHZ"],
    "victoria": ["YYJ"],
    "kelowna": ["YLW"],
    "saskatoon": ["YXE"],
    "regina": ["YQR"],
    "st john's": ["YYT"],
    "moncton": ["YQM"],
    "hamilton ca": ["YHM"],
    "london ca": ["YXU"],

    # --- Mexico & Central America ---
    "mexico city": ["MEX", "NLU", "TLC"],
    "guadalajara": ["GDL"],
    "monterrey": ["MTY"],
    "cancun": ["CUN"],
    "tijuana": ["TIJ"],
    "puerto vallarta": ["PVR"],
    "los cabos": ["SJD"],
    "merida": ["MID"],
    "leon": ["BJX"],
    "puebla": ["PBC"],
    "oaxaca": ["OAX"],
    "san luis potosi": ["SLP"],
    "chihuahua": ["CUU"],
    "hermosillo": ["HMO"],
    "veracruz": ["VER"],
    "villahermosa": ["VSA"],
    "tuxtla gutierrez": ["TGZ"],
    "panama city": ["PTY"],
    "san jose cr": ["SJO"],
    "liberia cr": ["LIR"],
    "guatemala city": ["GUA"],
    "san salvador": ["SAL"],
    "tegucigalpa": ["TGU", "XPL"],
    "roatan": ["RTB"],
    "managua": ["MGA"],
    "belize city": ["BZE"],

    # --- Caribbean ---
    "san juan": ["SJU"],
    "punta cana": ["PUJ"],
    "santo domingo": ["SDQ"],
    "santiago de los caballeros": ["STI"],
    "port-au-prince": ["PAP"],
    "havana": ["HAV"],
    "varadero": ["VRA"],
    "kingston": ["KIN"],
    "montego bay": ["MBJ"],
    "nassau": ["NAS"],
    "freeport": ["FPO"],
    "bridgetown": ["BGI"],
    "port of spain": ["POS"],
    "castries": ["SLU"],
    "saint lucia": ["UVF", "SLU"],
    "antigua": ["ANU"],
    "grenada": ["GND"],
    "dominica": ["DOM"],
    "st kitts": ["SKB"],
    "st maarten": ["SXM"],
    "aruba": ["AUA"],
    "curacao": ["CUR"],
    "bonaire": ["BON"],
    "guadeloupe": ["PTP"],
    "martinique": ["FDF"],
    "turks and caicos": ["PLS"],
    "grand cayman": ["GCM"],

    # --- South America ---
    "sao paulo": ["GRU", "CGH", "VCP"],
    "rio de janeiro": ["GIG", "SDU"],
    "brasilia": ["BSB"],
    "belo horizonte": ["CNF", "PLU"],
    "salvador": ["SSA"],
    "fortaleza": ["FOR"],
    "recife": ["REC"],
    "porto alegre": ["POA"],
    "curitiba": ["CWB"],
    "manaus": ["MAO"],
    "belem": ["BEL"],
    "florianopolis": ["FLN"],
    "goiania": ["GYN"],
    "vitoria": ["VIX"],
    "natal": ["NAT"],
    "buenos aires": ["EZE", "AEP"],
    "cordoba ar": ["COR"],
    "mendoza": ["MDZ"],
    "rosario": ["ROS"],
    "salta": ["SLA"],
    "bariloche": ["BRC"],
    "santiago": ["SCL"],
    "lima": ["LIM"],
    "cusco": ["CUZ"],
    "arequipa": ["AQP"],
    "bogota": ["BOG"],
    "medellin": ["MDE", "EOH"],
    "cali": ["CLO"],
    "cartagena": ["CTG"],
    "barranquilla": ["BAQ"],
    "bucaramanga": ["BGA"],
    "pereira": ["PEI"],
    "santa marta": ["SMR"],
    "quito": ["UIO"],
    "guayaquil": ["GYE"],
    "la paz bo": ["LPB"],
    "santa cruz de la sierra": ["VVI"],
    "cochabamba": ["CBB"],
    "asuncion": ["ASU"],
    "montevideo": ["MVD"],
    "punta del este": ["PDP"],
    "caracas": ["CCS"],
    "maracaibo": ["MAR"],

    # --- Africa (expanded) ---
    "cairo": ["CAI"],
    "alexandria": ["HBE"],
    "sharm el sheikh": ["SSH"],
    "hurghada": ["HRG"],
    "algiers": ["ALG"],
    "tunis": ["TUN"],
    "marrakesh": ["RAK"],
    "rabat": ["RBA"],
    "tangier": ["TNG"],
    "agadir": ["AGA"],
    "fes": ["FEZ"],
    "lagos": ["LOS"],
    "abuja": ["ABV"],
    "port harcourt": ["PHC"],
    "kano": ["KAN"],
    "accra": ["ACC"],
    "abidjan": ["ABJ"],
    "dakar": ["DSS"],
    "bamako": ["BKO"],
    "conakry": ["CKY"],
    "freetown": ["FNA"],
    "monrovia": ["ROB"],
    "banjul": ["BJL"],
    "ouagadougou": ["OUA"],
    "niamey": ["NIM"],
    "lome": ["LFW"],
    "cotonou": ["COO"],
    "douala": ["DLA"],
    "yaounde": ["NSI"],
    "libreville": ["LBV"],
    "malabo": ["SSG"],
    "sao tome": ["TMS"],
    "kinshasa": ["FIH"],
    "brazzaville": ["BZV"],
    "luanda": ["LAD"],
    "kigali": ["KGL"],
    "bujumbura": ["BJM"],
    "bangui": ["BGF"],
    "addis ababa": ["ADD"],
    "dar es salaam": ["DAR"],
    "kilimanjaro": ["JRO"],
    "zanzibar": ["ZNZ"],
    "entebbe": ["EBB"],
    "mombasa": ["MBA"],
    "maputo": ["MPM"],
    "harare": ["HRE"],
    "lusaka": ["LUN"],
    "lilongwe": ["LLW"],
    "antananarivo": ["TNR"],
    "mauritius": ["MRU"],
    "seychelles": ["SEZ"],
    "reunion": ["RUN"],
    "cape town": ["CPT"],
    "durban": ["DUR"],
    "port elizabeth": ["PLZ"],
    "east london": ["ELS"],
    "windhoek": ["WDH"],

    # --- Med Islands / Microstates ---
    "larnaca": ["LCA"],
    "paphos": ["PFO"],
    "malta": ["MLA"],
    "gibraltar": ["GIB"],
    "san marino": ["RMI"],  # via Rimini (nearest)
    "andorra": ["BCN", "TLS"],  # nearest major

}

# Metro "city" codes to constituent airports (round out behavior for LON/NYC/etc.)
METRO_TO_AIRPORTS: Dict[str, List[str]] = {
    "LON": ["LHR", "LGW", "LCY", "LTN", "STN", "SEN"],
    "PAR": ["CDG", "ORY", "BVA"],
    "MIL": ["MXP", "LIN", "BGY"],
    "ROM": ["FCO", "CIA"],
    "NYC": ["JFK", "LGA", "EWR"],
    "CHI": ["ORD", "MDW"],
    "TYO": ["HND", "NRT"],
    "SEL": ["ICN", "GMP"],
    "STO": ["ARN", "BMA"],
}

# If your API needs a *single* airport when a metro code is given, prefer this one:
PREFERRED_AIRPORT_FOR_METRO: Dict[str, str] = {
    "LON": "LHR",
    "PAR": "CDG",
    "MIL": "MXP",
    "ROM": "FCO",
    "NYC": "JFK",
    "CHI": "ORD",
    "TYO": "HND",
    "SEL": "ICN",
    "STO": "ARN",
}

# --- Public helpers -----------------------------------------------------------

def resolve_phrase_to_airports(phrase: str) -> Tuple[str, List[str]]:
    """
    Given any phrase ("istanbul", "lhr", "new york", "LON"),
    return (preferred_code, all_possible_codes).

    If an explicit IATA airport is found (3 letters), that wins.
    If a metro code (LON/NYC/ROM/…) is found, return the preferred single airport.
    Otherwise try to match city strings from CITY_TO_AIRPORTS.
    """
    if not phrase:
        return "", []

    # Check if it's already a 3-letter IATA code
    raw = phrase.strip().upper()
    if len(raw) == 3 and raw.isalpha():
        # Looks like an IATA code
        if raw in METRO_TO_AIRPORTS:
            alts = METRO_TO_AIRPORTS[raw]
            return PREFERRED_AIRPORT_FOR_METRO.get(raw, alts[0]), alts
        return raw, [raw]

    # Direct city match (case insensitive)
    city_key = phrase.strip().lower()
    if city_key in CITY_TO_AIRPORTS:
        alts = CITY_TO_AIRPORTS[city_key]
        # If first is a metro, map to preferred single airport
        first = alts[0]
        if first in METRO_TO_AIRPORTS:
            metro = first
            return PREFERRED_AIRPORT_FOR_METRO.get(metro, METRO_TO_AIRPORTS[metro][0]), METRO_TO_AIRPORTS[metro]
        return alts[0], alts

    # No match
    return "", []